Register multiple Redis client instances with Typescript
fastify/fastify-redis pull request #103
Opened 2021-07-30 09:07 UTC by CloudPower97

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

#### Description

Closes #102

2021-07-30 09:12 UTC, CloudPower97 commented
Hi, @Eomm I'm not sure why but all of the tests are failing no matter what.

I'm using the official [`Redis` Docker image](https://hub.docker.com/_/redis), exposing port `6379` to the host.

But I receive the following error:

````javascript
  node_modules/avvio/plugin.js                                                                       
  121 |       debug('timed out', name)                                                               
  122 |       timer = null                                                                           
> 123 |       const err = new Error(`${CODE_PLUGIN_TIMEOUT}: plugin did not start in time: ${name}. You may have forgotten to call 'done' function or to resolve a Promise`)
      | ------------------^                                                                          
  124 |       err.code = CODE_PLUGIN_TIMEOUT                                                         
  125 |       err.fn = func                                                                          
  126 |       done(err)   
````

Any ideas?

2021-07-30 09:42 UTC, climba03003 requested changes
Please remove the unnecessary linting change and please run ``npm run lint -- --fix` before commit.

2021-07-31 07:35 UTC, Eomm requested changes
I think it is missing a test here
https://github.com/fastify/fastify-redis/blob/master/test/types/index.ts

The CI is failing due the a test plan (check my suggestion)

2021-07-31 07:35 UTC, Eomm commented on test/test.js
> +  t.plan(2)
```suggestion
  t.plan(3)
```

2021-07-31 07:56 UTC, climba03003 reviewed
Can you add the typescript test in this file?
https://github.com/fastify/fastify-redis/blob/master/test/types/index.ts

2021-09-26 07:27 UTC, closed without merging