Swap ioredis for iovalkey
fastify/fastify-redis pull request #194
Opened 2024-04-01 22:00 UTC by bcomnes

Swap to a default redis client with a higher chance of getting maintained. iovalkey is a friendly fork maintained by @mcollina. I'm guessing this would be a breaking/major version bump if this lands.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2024-04-02 08:34 UTC, gurgunday requested changes
Changes lgtm but I don't know if we should land this to fastify-redis or create sth like fastify-iovalkey

CC @fastify/plugins

2024-04-02 08:39 UTC, simoneb commented
Just curious, the issue where this is being discussed in the ioredis repo mentions that they recommend migrating to the official client: https://github.com/redis/ioredis/issues/1870#issuecomment-2029351413.

Have we considered that, versus another community-maintained package which may end up having the same maintenance issues?

2024-04-02 08:47 UTC, gurgunday commented
> Just curious, the issue where this is being discussed in the ioredis repo mentions that they recommend migrating to the official client: https://github.com/redis/ioredis/issues/1870#issuecomment-2029351413.

Yeah honestly I had the same question in mind

It also applies to `fastify-rate-limit`, currently it accepts an ioredis instance

2024-04-02 08:49 UTC, climba03003 commented
I would go for the official one if it is a long term choice.
Using `ioredis` was a decision on 2018 #19, something might change now.

I also notice `redis` provide a benchmark script that we might want to try.

2024-04-02 08:50 UTC, simoneb commented
Oh I'm not challenging the original choice of ioredis by any means, the official client may not have even existed back then as far as I know. If we're to revise that decision now I think the official client might be the sensible option to choose, unless there are obvious reasons to avoid it (e.g. licensing or feature-completeness)

2024-04-02 08:55 UTC, climba03003 commented
> Oh I'm not challenging the original choice of ioredis by any means, the official client may not have even existed back then as far as I know.

I means the decision shown on the issue about using `ioredis` instead of `redis` is based on `performance` and `promise` support.
`promise` should not be a problem nowadays.
`performance` can be checked via https://github.com/redis/node-redis/tree/master/benchmark

It is a good time to re-visit the decision made in the past.

`redis` seems to provide more advance and up-to-date feature according to the issue you provide.

2024-04-02 08:58 UTC, mcollina commented
I've forked ioredis to iovalkey because:

1. I want to avoid being in the situation of being unable to fix ioredis in case the need arises. ioredis is essentially dead, but it's massively used.
1. I expect the server to break the protocol backward compatibility. It would be the best business move for them to make the server incompatible, making the official client to talk to the official database.
1. Ioredis seem to [significantly outperform](https://ably.com/blog/migrating-from-node-redis-to-ioredis) the official client.

None of the options looks good right now. I would likely hold for now, and possibly switch if the need arises.

2024-04-02 09:12 UTC, climba03003 commented
I don't like post with last updated date only, it seems to give a fault image to the author the content is up-to-date and latest.

It's last update is Jan 2, 2024 and all the others scripts is written or provided 3 years ago.
I judge the conclusion in the article is still up-to-date.

2024-04-02 10:17 UTC, climba03003 commented
Here the result of using https://github.com/poppinlp/node_redis-vs-ioredis

| Operation | redis(ms) | redis with multi(ms) | redis with batch(ms) |
| --------- | -------------- | ------------------------- | ------------------------- |
| set       | 1489.4949      | 87.3262                   | 83.2496                   |
| get       | 1425.5875      | 79.2133                   | 55.7291                   |
| hmset     | 1447.7094      | 73.6554                   | 71.0114                   |
| hgetall   | 1505.95        | 91.0191                   | 83.9859                   |
| incr      | 1437.0455      | 62.8249                   | 48.9377                   |
| keys      | 1447.0564      | 88.7329                   | 79.2056                   |

| Operation | ioredis(ms) | ioredis with multi(ms) | ioredis with pipeline(ms) |
| --------- | ----------- | ---------------------- | ------------------------- |
| set       | 1482.0976   | 82.4503                | 74.1322                   |
| get       | 1465.7855   | 70.7754                | 58.4931                   |
| hmset     | 1522.3452   | 96.9624                | 93.7096                   |
| hgetall   | 1559.0312   | 92.6324                | 83.0306                   |
| incr      | 1420.0616   | 57.512                 | 97.9488                   |
| keys      | 1499.0053   | 111.735                | 102.1956                  |

`redis` had an average time of 536.541ms
`ioredis` had an average time of 553.884ms

The benchmark may differ between platform, but it does not provide a extreme performance boost between `redis` and `ioredis`.

2024-04-02 10:21 UTC, simoneb commented
Well at least we know that performance is not an issue then

2024-04-02 11:08 UTC, mcollina commented
@climba03003 redis has autopipelining enabled by default, while ioredis doesn't. Can you check again with it enabled in ioredis?

2024-04-02 11:42 UTC, climba03003 commented
node_redis set: 1258.543ms
node_redis set with multi: 75.0749ms
node_redis set with batch: 68.3861ms
ioredis set: 1675.3534ms
ioredis set with multi: 99.8492ms
ioredis set with pipeline: 76.8969ms
node_redis get: 1209.5046ms
node_redis get with multi: 71.7987ms
node_redis get with batch: 62.7598ms
ioredis get: 1639.6578ms
ioredis get with multi: 81.0716ms
ioredis get with pipeline: 73.454ms
node_redis hmset: 1253.6383ms
node_redis hmset with multi: 84.0043ms
node_redis hmset with batch: 68.6202ms
ioredis hmset: 1957.5314ms
ioredis hmset with multi: 112.5022ms
ioredis hmset with pipeline: 103.87ms
node_redis hgetall: 1306.0386ms
node_redis hgetall with multi: 81.8917ms
node_redis hgetall with batch: 76.3933ms
ioredis hgetall: 1777.1176ms
ioredis hgetall with multi: 106.9713ms
ioredis hgetall with pipeline: 119.2135ms
node_redis incr: 1211.8546ms
node_redis incr with multi: 58.0944ms
node_redis incr with batch: 61.2377ms
ioredis incr: 1606.8474ms
ioredis incr with multi: 64.2966ms
ioredis incr with pipeline: 62.3032ms
node_redis keys: 1246.2134ms
node_redis keys with multi: 87.8436ms
node_redis keys with batch: 75.8015ms
ioredis keys: 1756.5684ms
ioredis keys with multi: 119.2338ms
ioredis keys with pipeline: 102.6729ms
.: Test Results :.
node_redis had an average time of 464.317ms
ioredis had an average time of 640.856ms
.: WINNER :.
The winner is node_redis with an average of 464.317ms

2024-04-02 23:08 UTC, bcomnes commented
I don't have a strong opinion on the matter, but it does seem like if we go the ioredis route, iovalkey might be the better long term solution (if @mcollina agrees). Is the official redis client a drop in replacement as well? I can make another PR with that when I have time.

2024-04-07 11:41 UTC, jsumners commented
> I don't know if we should land this to fastify-redis or create sth like fastify-iovalkey

Unless the API and protocol is different, I don't see a reason to create a completely new plugin with a different name.

2024-04-09 10:04 UTC, mcollina commented
I 100% expect the protocol to change in Redis 8.

2024-05-27 00:01 UTC, bcomnes commented
Closing until its more clear how to approach the issue.

2024-05-27 00:01 UTC, closed without merging